Feat add message notes
DAOptimate/web-app-backend pull request #3
Opened 2022-09-05 23:17 UTC by subject026

This adds a notes resource/endpoint plus tests.

2022-09-06 13:16 UTC, DavidRecheni requested changes

2022-09-06 13:16 UTC, DavidRecheni commented on src/note/note.controller.ts
> +// import { UpdateNoteDto } from './dto/update-note.dto';
No unused code

2022-09-06 13:16 UTC, DavidRecheni commented on src/message/message.controller.ts
> +  // Patch,
No unused code

2022-09-06 13:16 UTC, DavidRecheni commented on src/note/entities/note.entity.ts
> +@Entity({ name: 'note' })
I don't think the props are necessary

2022-09-06 13:16 UTC, DavidRecheni commented on src/note/entities/note.entity.ts
> +    onDelete: 'CASCADE',
!

2022-09-06 13:16 UTC, DavidRecheni commented on src/note/note.service.ts
> +  // findOne(id: number) {
No unused code

2022-09-06 13:16 UTC, DavidRecheni commented on test/note.e2e-spec.ts
> +  // let noteRepository: Repository<Note>;
No unused code

2022-09-06 22:08 UTC, subject026 commented
@DavidRecheni I've removed the table names from the entity decorators and the unused code.

Left the `onDelete: 'CASCADE'` option set on the note entity so that any notes attached to a message are deleted when that message is deleted.

2022-09-07 04:53 UTC, DavidRecheni commented
There's still some unused code, like in note.service

2022-09-07 06:59 UTC, subject026 commented
@DavidRecheni Alright that's gone now too!

2022-09-07 07:02 UTC, DavidRecheni approved these changes

2022-09-07 07:03 UTC, merged